[window]
opacity = 1

  [window.padding]
  x = 10
  y = 10

[colors.primary]
foreground = "#cecece"
background = "#0a0a0a"

[colors.normal]
black = "#1e1e1e"
red = "#ed8787"
green = "#87ed96"
yellow = "#efe256"
blue = "#5674ef"
magenta = "#790ed1"
cyan = "#4ed1d8"
white = "#cecece"

[colors.bright]
black = "#1e1e1e"
red = "#ed8787"
green = "#87ed96"
yellow = "#efe256"
blue = "#5674ef"
magenta = "#790ed1"
cyan = "#4ed1d8"
white = "#cecece"

[font.normal]
family = "DroidSansM Nerd Font Mono"

